### ISSUE TITLE
Keplerian Orbital motion vs Linear approximation

### ISSUE THREAD

**Issue by valboz** [microlensing-data-challenge/data-challenge-1#1]
Hi

I read that the evaluated orbital motion entries are only ds/dt and d\alpha/dt. While a linear approximation may work well for slow enough orbital motion and is a useful starting point for modeling, we should always be aware that this approximation does not correspond to any physical trajectory. So, if light curves in the data challenge have been created with this simple approximation rather than a full Keplerian motion, they are actually unphysical. If this is the case, this is a serious problem. Can you please comment?

Best wishes

 Valerio

**Comment by rachel3834** [comment]
This comment has been address as a question to the Data Challenge Organizer team.  Please refer to https://github.com/orgs/microlensing-data-challenge/teams/challenge-organizer/discussions/2
